# Generated by Django 4.2.7 on 2025-11-06 07:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.CharField(db_index=True, max_length=100)),
                ('invoice_date', models.DateField()),
                ('vendor_name', models.CharField(max_length=255)),
                ('vendor_gstin', models.CharField(db_index=True, max_length=15)),
                ('billed_company_gstin', models.CharField(max_length=15)),
                ('grand_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING_ANALYSIS', 'Pending Analysis'), ('CLEARED', 'Cleared'), ('HAS_ANOMALIES', 'Has Anomalies')], db_index=True, default='PENDING_ANALYSIS', max_length=20)),
                ('gst_verification_status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('file_path', models.FileField(upload_to='invoices/')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('normalized_key', models.CharField(db_index=True, max_length=255)),
                ('hsn_sac_code', models.CharField(db_index=True, max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('billed_gst_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='invoice_processor.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='ComplianceFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_type', models.CharField(choices=[('DUPLICATE', 'Duplicate'), ('ARITHMETIC_ERROR', 'Arithmetic Error'), ('HSN_MISMATCH', 'HSN Rate Mismatch'), ('UNKNOWN_HSN', 'Unknown HSN/SAC Code'), ('PRICE_ANOMALY', 'Price Anomaly')], db_index=True, max_length=50)),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical'), ('WARNING', 'Warning'), ('INFO', 'Info')], db_index=True, max_length=10)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_flags', to='invoice_processor.invoice')),
                ('line_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoice_processor.lineitem')),
            ],
        ),
        migrations.AddIndex(
            model_name='lineitem',
            index=models.Index(fields=['normalized_key'], name='invoice_pro_normali_c97388_idx'),
        ),
        migrations.AddIndex(
            model_name='lineitem',
            index=models.Index(fields=['hsn_sac_code'], name='invoice_pro_hsn_sac_a016a1_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['vendor_gstin', 'invoice_id'], name='invoice_pro_vendor__188605_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['uploaded_at'], name='invoice_pro_uploade_e0fd76_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status'], name='invoice_pro_status_74dc3c_idx'),
        ),
        migrations.AddIndex(
            model_name='complianceflag',
            index=models.Index(fields=['flag_type', 'severity'], name='invoice_pro_flag_ty_c2dbf5_idx'),
        ),
        migrations.AddIndex(
            model_name='complianceflag',
            index=models.Index(fields=['created_at'], name='invoice_pro_created_7af38c_idx'),
        ),
    ]
