# Generated by Django 4.2.7 on 2025-11-06 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_processor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complianceflag',
            name='flag_type',
            field=models.CharField(choices=[('DUPLICATE', 'Duplicate'), ('ARITHMETIC_ERROR', 'Arithmetic Error'), ('HSN_MISMATCH', 'HSN Rate Mismatch'), ('UNKNOWN_HSN', 'Unknown HSN/SAC Code'), ('PRICE_ANOMALY', 'Price Anomaly'), ('SYSTEM_ERROR', 'System Error')], db_index=True, max_length=50),
        ),
    ]
