# Generated by Django 4.2.7 on 2025-11-07 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invoice_processor', '0002_alter_complianceflag_flag_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('facebook_connected', models.BooleanField(default=False)),
                ('google_connected', models.BooleanField(default=False)),
                ('enable_sound_effects', models.BooleanField(default=True)),
                ('enable_animations', models.BooleanField(default=True)),
                ('enable_notifications', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='ai_confidence_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='extraction_failure_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='extraction_method',
            field=models.CharField(choices=[('AI', 'AI Extracted'), ('MANUAL', 'Manual Entry')], default='AI', max_length=20),
        ),
        migrations.CreateModel(
            name='InvoiceHealthScore',
            fields=[
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='health_score', serialize=False, to='invoice_processor.invoice')),
                ('overall_score', models.DecimalField(decimal_places=1, max_digits=3)),
                ('status', models.CharField(choices=[('HEALTHY', 'Healthy (8.0-10.0)'), ('REVIEW', 'Review (5.0-7.9)'), ('AT_RISK', 'At Risk (0.0-4.9)')], max_length=20)),
                ('data_completeness_score', models.DecimalField(decimal_places=2, max_digits=4)),
                ('verification_score', models.DecimalField(decimal_places=2, max_digits=4)),
                ('compliance_score', models.DecimalField(decimal_places=2, max_digits=4)),
                ('fraud_detection_score', models.DecimalField(decimal_places=2, max_digits=4)),
                ('ai_confidence_score_component', models.DecimalField(decimal_places=2, max_digits=4)),
                ('key_flags', models.JSONField(default=list)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='invoice_pro_status_a9056e_idx'), models.Index(fields=['overall_score'], name='invoice_pro_overall_24bd6b_idx')],
            },
        ),
        migrations.CreateModel(
            name='InvoiceBatch',
            fields=[
                ('batch_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_files', models.IntegerField()),
                ('processed_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('PARTIAL_FAILURE', 'Partial Failure')], default='PROCESSING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Invoice Batches',
            },
        ),
        migrations.CreateModel(
            name='GSTCacheEntry',
            fields=[
                ('gstin', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('legal_name', models.CharField(max_length=255)),
                ('trade_name', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(max_length=50)),
                ('registration_date', models.DateField(blank=True, null=True)),
                ('business_constitution', models.CharField(blank=True, max_length=100, null=True)),
                ('principal_address', models.TextField(blank=True, null=True)),
                ('einvoice_status', models.CharField(blank=True, max_length=50, null=True)),
                ('last_verified', models.DateTimeField(auto_now=True)),
                ('verification_count', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'GST Cache Entry',
                'verbose_name_plural': 'GST Cache Entries',
                'indexes': [models.Index(fields=['legal_name'], name='invoice_pro_legal_n_64a9ce_idx'), models.Index(fields=['status'], name='invoice_pro_status_1d6f81_idx')],
            },
        ),
        migrations.CreateModel(
            name='APIKeyUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_hash', models.CharField(max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('usage_count', models.IntegerField(default=0)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('exhausted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'API Key Usage',
                'verbose_name_plural': 'API Key Usage Records',
                'indexes': [models.Index(fields=['is_active'], name='invoice_pro_is_acti_5265d7_idx')],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='invoice_processor.invoicebatch'),
        ),
        migrations.CreateModel(
            name='InvoiceDuplicateLink',
            fields=[
                ('duplicate_invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='duplicate_link', serialize=False, to='invoice_processor.invoice')),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('original_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicates', to='invoice_processor.invoice')),
            ],
            options={
                'indexes': [models.Index(fields=['original_invoice'], name='invoice_pro_origina_f20b3f_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='invoicebatch',
            index=models.Index(fields=['user', 'created_at'], name='invoice_pro_user_id_ccac80_idx'),
        ),
        migrations.AddIndex(
            model_name='invoicebatch',
            index=models.Index(fields=['status'], name='invoice_pro_status_d0e794_idx'),
        ),
    ]
