# Generated by Django 4.2.7 on 2025-11-07 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invoice_processor', '0003_userprofile_invoice_ai_confidence_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureNotificationSignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255)),
                ('feature_name', models.CharField(max_length=100)),
                ('signed_up_at', models.DateTimeField(auto_now_add=True)),
                ('notified', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feature Notification Signup',
                'verbose_name_plural': 'Feature Notification Signups',
                'indexes': [models.Index(fields=['feature_name', 'notified'], name='invoice_pro_feature_4aaff7_idx'), models.Index(fields=['email'], name='invoice_pro_email_8eb9ee_idx')],
                'unique_together': {('email', 'feature_name')},
            },
        ),
    ]
