# Generated by Django 4.2.7 on 2025-11-08 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_processor', '0004_featurenotificationsignup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicehealthscore',
            name='ai_confidence_score_component',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='invoicehealthscore',
            name='compliance_score',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='invoicehealthscore',
            name='data_completeness_score',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='invoicehealthscore',
            name='fraud_detection_score',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='invoicehealthscore',
            name='verification_score',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
